sudo: required

branches:
  only:
  - master
  - development

services:
  - mysql

matrix:
  include:
    - language: python
      python: 3.6
      cache:
        pip3: true
      install:
        - pip3 install django coverage djangorestframework Pillow requests pymysql mysqlclient mysql-python django-cors-headers
      before_script:
        - cd backend
        - mysql -u root -e 'CREATE DATABASE plainplane;'
        - mysql -u root -e "CREATE USER 'swpp'@'localhost' IDENTIFIED BY 'iluvswpp';"
        - mysql -u root -e "GRANT ALL ON * . * TO 'swpp'@'localhost';"
        - python3 manage.py makemigrations
        - python3 manage.py migrate
      script:
        - python3 manage.py test
      after_script:
        - cd ..

    - language: node_js
      node_js: 8.8
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      cache:
        npm: true
        directories:
          - frontend/node_modules
      before_install:
        - export CHROME_BIN=/usr/bin/google-chrome
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - cd frontend
      install:
        - npm install
        - npm install coveralls
        - npm install -g @angular/cli
      script:
        - ng test --code-coverage --watch false
        - ng e2e
      after_script:
        - cd ..
