sudo: required

branches:
  only:
  - master
  - development

matrix:
  include:
    - language: python
      python: 3.6
      cache:
        pip3: true
      install:
        - pip3 install django coverage coveralls djangorestframework django-enumfield Pillow
      before_script:
        - cd backend
        - python3 manage.py migrate
      script:
        - coverage run --branch --source="./plain_plane" manage.py test
      after_success:
        - coveralls
      after_script:
        - cd ..
